"""Deterministic statistical baseline and temporal validation kernel."""

from btg_ai_trader.statistical_baselines.baselines import (
    BaseStatisticalBaseline,
    ConstantBaseline,
    HistoricalMeanBaseline,
    HistoricalMedianBaseline,
    HistoricalPriorProbabilityBaseline,
    LastKnownClassBaseline,
    MajorityClassBaseline,
    PersistenceBaseline,
    StatisticalBaseline,
)
from btg_ai_trader.statistical_baselines.boundaries import (
    EvaluationBoundary,
    TemporalFold,
    WalkForwardPlan,
)
from btg_ai_trader.statistical_baselines.calibration import (
    CalibrationBin,
    CalibrationReport,
    compute_calibration,
)
from btg_ai_trader.statistical_baselines.comparison import (
    Comparator,
    EvaluationHistory,
    ModelComparisonResult,
    ProtectedEvidenceConsumption,
    ProtectedEvidenceUse,
    SearchFamily,
)
from btg_ai_trader.statistical_baselines.domain import (
    CandidateIdentity,
    CausalLeakageError,
    EvaluationRole,
    ParityViolationError,
    PredictionInput,
    PredictionResult,
    ProtectedEvidenceReuseError,
    StatisticalSample,
    TargetSemantics,
)
from btg_ai_trader.statistical_baselines.evaluation import (
    AggregateEvaluationResult,
    FoldAggregationPolicy,
    FoldEvaluationResult,
    FoldStabilityDiagnostics,
    StatisticalEvaluationEngine,
)
from btg_ai_trader.statistical_baselines.metrics import (
    DEFAULT_NUMERIC_POLICY,
    NumericPolicy,
    accuracy_score,
    base_rate,
    brier_score,
    class_prevalence,
    compute_continuous_metrics,
    confusion_matrix_counts,
    mean_absolute_error,
    mean_bias,
    mean_squared_error,
    root_mean_squared_error,
)
from btg_ai_trader.statistical_baselines.provenance import (
    EvaluationProvenanceRecord,
    StatisticalEvaluationInputBoundary,
    StatisticalEvaluationManifest,
)
from btg_ai_trader.statistical_baselines.splits import (
    EmbargoPolicy,
    PurgePolicy,
    SplitPlanConfig,
    WalkForwardPlanner,
    WindowPolicy,
)

__all__ = [
    "DEFAULT_NUMERIC_POLICY",
    "AggregateEvaluationResult",
    "BaseStatisticalBaseline",
    "CalibrationBin",
    "CalibrationReport",
    "CandidateIdentity",
    "CausalLeakageError",
    "Comparator",
    "ConstantBaseline",
    "EmbargoPolicy",
    "EvaluationBoundary",
    "EvaluationHistory",
    "EvaluationProvenanceRecord",
    "EvaluationRole",
    "FoldAggregationPolicy",
    "FoldEvaluationResult",
    "FoldStabilityDiagnostics",
    "HistoricalMeanBaseline",
    "HistoricalMedianBaseline",
    "HistoricalPriorProbabilityBaseline",
    "LastKnownClassBaseline",
    "MajorityClassBaseline",
    "ModelComparisonResult",
    "NumericPolicy",
    "ParityViolationError",
    "PersistenceBaseline",
    "PredictionInput",
    "PredictionResult",
    "ProtectedEvidenceConsumption",
    "ProtectedEvidenceReuseError",
    "ProtectedEvidenceUse",
    "PurgePolicy",
    "SearchFamily",
    "SplitPlanConfig",
    "StatisticalBaseline",
    "StatisticalEvaluationEngine",
    "StatisticalEvaluationInputBoundary",
    "StatisticalEvaluationManifest",
    "StatisticalSample",
    "TargetSemantics",
    "TemporalFold",
    "WalkForwardPlan",
    "WalkForwardPlanner",
    "WindowPolicy",
    "accuracy_score",
    "base_rate",
    "brier_score",
    "class_prevalence",
    "compute_calibration",
    "compute_continuous_metrics",
    "confusion_matrix_counts",
    "mean_absolute_error",
    "mean_bias",
    "mean_squared_error",
    "root_mean_squared_error",
]
